sudo: false
language: c++
os: linux

cache:
  apt: true

matrix:
  include:
    - compiler: gcc
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
      
    - compiler: clang
      env: CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-precise-3.7

env:
  global:
    - BUILD_DIR_NAME=build
    - DOC_BRANCH=master

cache:
  directories:
    - $HOME/cmake
    - $HOME/doxygen

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python-yaml
      - graphviz

before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-credentials.sh
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
